name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: rangefunc

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - run: make cover
